### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by lolminerxmrig** [shahabbai/PersianPlateRecog#1]
hi.
me add new car images but not load and not read image or license plate detection recognition

**Comment by shahabbai** [comment]
> hi. me add new car images but not load and not read image or license plate detection recognition

Hello. Thanks for your feedback. Can you explain more about it? which options did you run and what is the error? This is Demo of my work there is 100% bug and some issue. I will fix it. but explain more about the issue.

**Comment by lolminerxmrig** [comment]
1.need export txt
2. change load image
main.py
[ERROR:0@2.892] global cap.cpp:166 cv::VideoCapture::open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): assets/detected_plate.jpg in function 'cv::icvExtractPattern'


[ERROR:0@3.472] global cap.cpp:597 cv::VideoWriter::open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap_images.cpp:267: error: (-215:Assertion failed) number < max_number in function 'cv::icvExtractPattern'



Traceback (most recent call last):
  File "C:\Users\A\Downloads\Compressed\PersianPlateRecog-master\PersianPlateRecog-master\main.py", line 98, in <module>
    output = model_object(source, show=False, conf=0.75)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\ultralytics\yolo\engine\model.py", line 111, in __call__
    return self.predict(source, stream, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\UsersA\AppData\Roaming\Python\Python311\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\ultralytics\yolo\engine\model.py", line 253, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\ultralytics\yolo\engine\predictor.py", line 184, in __call__
    return list(self.stream_inference(source, model))  # merge list of Result into one
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\UsersA\AppData\Roaming\Python\Python311\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
               ^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\ultralytics\yolo\engine\predictor.py", line 215, in stream_inference
    self.setup_source(source if source is not None else self.args.source)
  File "C:\Python311\Lib\site-packages\ultralytics\yolo\engine\predictor.py", line 197, in setup_source
    self.dataset = load_inference_source(source=source, imgsz=self.imgsz, vid_stride=self.args.vid_stride)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\ultralytics\yolo\data\build.py", line 164, in load_inference_source
    dataset = LoadImages(source, imgsz=imgsz, vid_stride=vid_stride)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\ultralytics\yolo\data\dataloaders\stream_loaders.py", line 169, in __init__
    raise FileNotFoundError(f'{p} does not exist')
FileNotFoundError: C:\UsersA\Downloads\Compressed\PersianPlateRecog-master\PersianPlateRecog-master\assets\detected_plate.jpg does not exist

**Comment by lolminerxmrig** [comment]
![image](https://github.com/shahabbai/PersianPlateRecog/assets/108659226/f1b0a0aa-5d8c-45d0-84ce-705311f1f70b)

**Comment by lolminerxmrig** [comment]
![image](https://github.com/shahabbai/PersianPlateRecog/assets/108659226/87cc6b6a-af34-464b-ad24-35dd66da2f52)

**Comment by lolminerxmrig** [comment]
![image](https://github.com/shahabbai/PersianPlateRecog/assets/108659226/cd47b646-0394-4138-a2cf-717ab16a7de8)

**Comment by shahabbai** [comment]
> ![image](https://user-images.githubusercontent.com/108659226/241416162-cd47b646-0394-4138-a2cf-717ab16a7de8.png)

There was a mistake in charclassnames list in the main.py and because of that the output show the wrong character. i fixed it now. use git pull in the command to update the code or clone again and test it. Thanks

**Comment by lolminerxmrig** [comment]
thanks very good.
can add export txt?
can add multi item scan?

**Comment by shahabbai** [comment]
> thanks very good. can add export txt? can add multi item scan?

![output_20230528132539](https://github.com/shahabbai/PersianPlateRecog/assets/133869713/69f8da3c-fe4a-4061-b1ee-8f1886c34919)

I'm doing some optimization on the output visualization. Yes it's possible to log and export plates to txt file or csv file. and your answer for your second question is in the image.

**Comment by lolminerxmrig** [comment]
very great
But I have a lot of files. If possible, I want to give the address of the directory and get the output.
txt or csv or sqlite or sql server.

**Comment by shahabbai** [comment]
maybe in future add a logger to save the plates.

**Comment by lolminerxmrig** [comment]
ok.
and load or read folder files?
